<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Addressing Callback Hell using Promises</title>
  </head>
  <body>
    <h1>Addressing Callback Hell using Promises</h1>
    <script>
      // Promise: object that manage asynchronous operations.
      // Syntax: new Promise((resolve, reject) => {})
      // pending:
      // resolve: task completed.
      // reject: task failed.
      const task1 = () => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const taskCompleted = true;
            if (taskCompleted) {
              resolve("Task 1 is complete.");
            } else {
              reject("Task 1 failed.");
            }
          }, 2000);
        });
      };

      const task2 = () => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const taskCompleted = true;
            if (taskCompleted) {
              resolve("Task 2 is complete.");
            } else {
              reject("Task 2 failed.");
            }
          }, 3000);
        });
      };
      const task3 = () => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const taskCompleted = true;
            if (taskCompleted) {
              resolve("Task 3 is complete.");
            } else {
              reject("Task 3 failed.");
            }
          }, 3000);
        });
      };

      task1()
        .then((value) => {
          console.log(value);
          return task2();
        })
        .then((value) => {
          console.log(value);
          return task3();
        })
        .then((value) => {
          console.log(value);
          console.log("All task complete.");
        });

      task1()
        .then((value) => {
          console.log(value);
          return task2();
        })
        .then((value) => {
          console.log(value);
          return task3();
        })
        .then((value) => {
          console.log(value);
          console.log("All task complete.");
        })
        .catch((error) => {
          console.error("Error:", error);
        })
        .finally(() => {
          console.log(
            "This will be executed, regardless of the success or failure."
          );
        });
    </script>
  </body>
</html>
